name: Deploy to AWS EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Save SSH key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Test SSH connection to EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "echo '✅ SSH connection successful'"

      - name: SSH into EC2 and deploy
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            set -e  # Exit on any error

            cd /home/ec2-user/Chatbot-backend

            git pull origin main

            python3 -m venv venv
            source venv/bin/activate

            pip install --upgrade pip
            pip install -r requirements.txt

            playwright install

            sudo systemctl restart fastapi
          EOF