version: '3.8'

services:
  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_DB: test_workmate
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./token_tracking_schema_postgresql.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_workmate"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  supabase-test:
    image: supabase/supabase:latest
    environment:
      POSTGRES_PASSWORD: test_pass
      JWT_SECRET: test_jwt_secret
      ANON_KEY: test_anon_key
      SERVICE_ROLE_KEY: test_service_role_key
    ports:
      - "54321:8000"
    depends_on:
      postgres-test:
        condition: service_healthy
    volumes:
      - supabase_test_data:/var/lib/supabase

volumes:
  postgres_test_data:
  redis_test_data:
  supabase_test_data: