version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: workmate-elasticsearch
    environment:
      - node.name=workmate-elasticsearch
      - cluster.name=workmate-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-headers="*"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - workmate-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: workmate-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_SYSTEM_PASSWORD=changeme
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - workmate-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 日本語解析プラグインのインストール用の初期化コンテナ
  elasticsearch-plugins:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: workmate-elasticsearch-plugins
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    command: >
      bash -c "
        echo 'Installing Japanese analysis plugins...'
        elasticsearch-plugin install analysis-kuromoji --batch || true
        elasticsearch-plugin install analysis-icu --batch || true
        echo 'Plugins installation completed'
      "
    networks:
      - workmate-network
    profiles:
      - plugins

volumes:
  elasticsearch_data:
    driver: local

networks:
  workmate-network:
    driver: bridge 