name: Deploy Frontend to AWS EC2

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'Chatbot-Frontend-main/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd Chatbot-Frontend-main
        npm ci
        
    - name: Create .env file
      run: |
        cd Chatbot-Frontend-main
        cat > .env << 'EOF'
        GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
        COMPANY_NAME="NTT AT"
        
        SUPABASE_URL=${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
        
        VITE_API_URL=${{ secrets.VITE_API_URL }}
        VITE_GOOGLE_DRIVE_CLIENT_ID=${{ secrets.VITE_GOOGLE_DRIVE_CLIENT_ID }}
        VITE_GOOGLE_DRIVE_API_KEY=${{ secrets.VITE_GOOGLE_DRIVE_API_KEY }}
        VITE_GOOGLE_REDIRECT_URI=${{ secrets.VITE_GOOGLE_REDIRECT_URI }}
        EOF
        
    - name: Build application
      run: |
        cd Chatbot-Frontend-main
        npm run build
        
    - name: Create deployment archive
      run: |
        cd Chatbot-Frontend-main
        tar -czf ../frontend-dist.tar.gz dist/
        
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          # バックアップ作成
          sudo cp -r /home/ec2-user/Chatbot-Frontend-main/dist /home/ec2-user/Chatbot-Frontend-main/dist.backup.$(date +%Y%m%d_%H%M%S) || true
          
          # 新しいdistディレクトリを準備
          rm -rf /home/ec2-user/frontend-dist-new
          mkdir -p /home/ec2-user/frontend-dist-new
          
    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        source: "frontend-dist.tar.gz"
        target: "/home/ec2-user/"
        
    - name: Extract and restart
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          # ファイル展開
          cd /home/ec2-user
          tar -xzf frontend-dist.tar.gz -C frontend-dist-new
          
          # アトミックな置換
          rm -rf /home/ec2-user/Chatbot-Frontend-main/dist
          mv /home/ec2-user/frontend-dist-new/dist /home/ec2-user/Chatbot-Frontend-main/
          
          # クリーンアップ
          rm -rf /home/ec2-user/frontend-dist-new
          rm -f /home/ec2-user/frontend-dist.tar.gz
          
          # PM2再起動
          pm2 restart chatbot-frontend || pm2 start /home/ec2-user/Chatbot-Frontend-main/dist --name chatbot-frontend
          
          echo "✅ デプロイ完了" 